# Project Report Draft 1

## Introduction

In this report, we aim to explore housing affordability in Metro Vancouver, through analysis of the “Housing Affordability for New Homeowners in B.C., Census Metropolitan Areas Quarterly Data 2025 Q3” dataset obtained from the B.C. Data Catalogue. The complete dataset contains data from all major cities in BC, gathered quarterly. The data was gathered to improve affordability across BC. This data was collected through a combined effort by Statistics Canada, Bank of Canada and BC Assessment, and compiled by BC Stats. They used informational sources such as CRA tax returns, CPI surveys, and property information gathered via BC assessments.
Source: https://catalogue.data.gov.bc.ca/dataset/b-c-housing-affordability/resource/a71e6838-cda1-4acb-adfb-8515c4f9fec9

As students currently struggling with affordability in Metro Vancouver, we wanted to investigate housing affordability trends in this area and its association to variables such as housing prices, the prime rate, and family income. Specifically, we want to know how interest rates and median family income affect median housing price, after accounting for housing type and number of resales. This will help us understand the key factors driving market price, and potentially derive our own conclusions on affordability trends.

### Variables

| Variable Name(s) | Type | Description |
|------------------|------|-------------|
| CMA ID | Integer | Census metropolitan area ID/Name assigned by Statistics Canada, which corresponds to population centres. See the definition on their website. |
| CMA NAME | Categorical | Census metropolitan area ID/Name assigned by Statistics Canada, which corresponds to population centres. |
| YEAR | Integer | Each row is specified by a combination of YEAR, QUARTER and HOUSING TYPE. YEAR value ranges from 2000 to 2025. |
| QUARTER | Integer | QUARTER value ranges from 1 to 4 (Q1–Q4), up to 2025 Q3. |
| HOUSING TYPE | Categorical | HOUSING TYPE values is one of the values in this set: {Single-detached, Apartment, Row Housing, All Housing Types}. |
| MEDIAN HOUSING PRICE | Integer | Sale price for a particular year/quarter/house-type. (CAD) |
| MEDIAN AFTER TAX FAMILY ANNUAL INCOME | Float | Estimated quarterly median family income. (CAD) |
| PRIME INTEREST RATE | Float | Base loan interest rate used to estimate mortgage rates. (%) |
| MORTGAGE PAYMENT PERCENT INCOME (MPPI) | Float | Affordability metric based on median after-income tax, home price, minimum down payment, and 25-year variable rate mortgage (based on prime). Higher means less affordable (% of income). |
| HISTORIC PAYMENT PERCENT INCOME | Float | Long-term running average of MPPI used as benchmark, calculated using MPPI from 2000–2025. |
| NUMBER OF RESALES | Integer | Resale count per quarter. (Count of homes). |

In [17]:
library(readr)
library(dplyr)
library(stringr)
library(janitor)
data = read.csv2("bc-data-catalogue-cma-2025-q3.csv", header=TRUE, sep=",")
head(data)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘janitor’


The following objects are masked from ‘package:stats’:

    chisq.test, fisher.test

  CMA.ID CMA.NAME             YEAR QUARTER HOUSING.TYPE
1 932    Abbotsford - Mission 2000 1       All housing types
2 932    Abbotsford - Mission 2000 1       Condos
3 932    Abbotsford - Mission 2000 1       Single-detached
4 932    Abbotsford - Mission 2000 1       Townhouses
5 944    Campbell River       2000 1       All housing types
6 944    Campbell River       2000 1       Condos
  MEDIAN.HOUSING.PRICE MEDIAN.AFTER.TAX.ANNUAL.FAMILY.INCOME
1 180000               40110
2 85000                40110
3 198000               40110
4 159839               40110
5 136000               44950
6 88250                44950
  PRIME.INTEREST.RATE MORTGAGE.PAYMENT.PERCENT.INCOME
1 6.673076923         35.17394885
2 6.673076923         16.60992029
3 6.673076923         38.69134374
4 6.673076923         31.23427117
5 6.673076923         23.71431023
6 6.673076923         15.38814616
  HISTORIC.PAYMENT.PERCENT.INCOME NUMBER.OF.RESALES
1 39.8580484                      211
2 20.09532322                      25
3 49.93104757                     151
4 32.71122748                      35
5 28.83969156                      61
6 18.33500271                      10

In [21]:
vancouver_data <- data |>
    filter(CMA.NAME == "Vancouver") |>
    clean_names()
head(vancouver_data)

  cma_id cma_name  year quarter housing_type      median_housing_price
1 933    Vancouver 2000 1       All housing types 239500
2 933    Vancouver 2000 1       Condos            159839
3 933    Vancouver 2000 1       Single-detached   288500
4 933    Vancouver 2000 1       Townhouses        205781
5 933    Vancouver 2000 2       All housing types 244492.9386
6 933    Vancouver 2000 2       Condos            157699.6995
  median_after_tax_annual_family_income prime_interest_rate
1 42730                                 6.673076923
2 42730                                 6.673076923
3 42730                                 6.673076923
4 42730                                 6.673076923
5 42730                                 7.269230769
6 42730                                 7.269230769
  mortgage_payment_percent_income historic_payment_percent_income
1 43.93128529                     46.34979114
2 29.31913449                     33.52101857
3 52.91931443                     73.63157159
4 37.74623724                     42.89966917
5 47.32920704                     46.34979114
6 30.52767811                     33.52101857
  number_of_resales
1 3944
2 1245
3 2146
4  553
5 5615
6 1567

The data was almost completely clean from the start, there was nothing missing, and no duplicates. Since we're focusing only on Metro Vancouver, the data was filtered to only contain it.